site_name: IBM Cloud Automation
site_url: https://ibm-cloud-automation.github.io
site_author: Raimond van Stijn
repo_name: ibm-cloud-automation.github.io
repo_url: https://github.com/ibm-cloud-automation/ibm-cloud-automation.github.io.git
theme:
  name: material
nav:
  - Home: index.md
  - GitOps Basics: gitops/basics.md
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
